### ISSUE TITLE
Make the logo more distinct from the Orchard Core logo

### ISSUE THREAD

**Issue by Piedone** [OrchardCoreContrib/OrchardCoreContrib#20]
The OrchardCoreContrib logo is almost the Orchard Core logo, and the difference in a smaller image size is really small, like on nuget.org:

![image](https://user-images.githubusercontent.com/1976647/227610654-679a1c36-ce9a-4b67-87fc-48150d9b72c1.png)

This makes it easy to mistake the project as being part of Orchard Core proper.

**Comment by hishamco** [comment]
Oops, seems I didn't notice this issue. I will try to work on this, but if you have a suggestion it will be nice, I see many Contrib projects adding "Contrib" to the logo

**Comment by Piedone** [comment]
Building on the Orchard Core logo is not entirely clear legally anyway I think, see the license: https://github.com/OrchardCMS/OrchardCore/blob/main/LICENSE So, the best would be to have a completely unique logo.

**Comment by hishamco** [comment]
> Building on the Orchard Core logo is not entirely clear legally anyway I think

The intention is not to make a commercial product so far. I'm not sure if having the license comment is enough to use some of the OC sources or not. Should I change the license to `BSD 3-Clause` instead?

 I might contact @sebastienros about this

> So, the best would be to have a completely unique logo.

I will think about it, thanks

**Comment by Piedone** [comment]
Your intentions or the license of Orchard Core Contrib are not relevant for this. Rather, the copyright and this clause in Orchard's license:

> Neither the name of Orchard nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

**Comment by hishamco** [comment]
What's your suggestion about the License in this case?

**Comment by Piedone** [comment]
For this issue, it doesn't matter. Otherwise, I'd also use 3-clause BSD.

**Comment by hishamco** [comment]
I just changed the license for `OrchardCoreContrib`, `OrchardCoreContrib.Modules`, and `OrchardCoreContrib.Themes` to BSD-3 instead and leave MIT for `OrchardCoreContrib.PoExtractor`

**Comment by hishamco** [comment]
@Piedone while I changed the license do you think there's any issue, or should I contact someone

This is my humble attempt to design a new logo

![Screenshot 2024-04-25 082452](https://github.com/OrchardCoreContrib/OrchardCoreContrib/assets/3237266/3f7e0405-650b-4f6d-8130-2000f5c376fd)

![Screenshot 2024-04-25 082946](https://github.com/OrchardCoreContrib/OrchardCoreContrib/assets/3237266/d6ce556c-2709-422a-a71d-39cde5fdf512)

**Comment by Piedone** [comment]
I think the second one is quite nice!
